### PR TITLE
Update for alpine linux

### PR DESCRIPTION
**Pull request by mattfidler**
Match windows reqirements

### CODE REVIEW

**Comment by mattfidler** [comment]
Hi, @bastistician  

Let me know if this works for you.  If so, I will adapt it for all other work-arounds.

I can submit this to CRAN now, since it has been over 30 days since my last submit  with `rxode2ll`.  For the other packages I may have to wait until Dec or next year.

**Comment by bastistician** [comment]
Thanks for working on this portability issue.
The change in this PR won't work as intended. `Makevars.win` isn't used on linux.
```
--------[begin src/Makevars]--------
cat: can't open 'src/Makevars': No such file or directory
--------[end src/Makevars]--------
```

**Comment by mattfidler** [comment]
This **should** work for alpine linux.

**Comment by mattfidler** [comment]
https://github.com/nlmixr2/rxode2/pull/809
https://github.com/nlmixr2/nlmixr2extra/pull/74
https://github.com/nlmixr2/nlmixr2est/pull/495
https://github.com/nlmixr2/babelmixr2/pull/147

**Comment by bastistician** [comment]
Ah I see, so `-isystem` was intended as a workaround for PopOS? It seems `-I` will now be used everywhere but on that OS. Note that the PRETTY_NAME or NAME info from `/etc/os-release` is already stored in `utils::osVersion`, so you could just check that string.

Anyway, I can confirm that the current version of this PR installs and checks fine on Alpine Linux. Thanks!

**Comment by mattfidler** [comment]
> Ah I see, so -isystem was intended as a workaround for PopOS? 

No, actually I meant this for all systems that support `-isystem`; but since I develop on `PopOS`, I want to use it there at the very least.  The -`isystem` flag suppresses all non `rxode2ll` system messages that I need to take care of instead of showing the many, many stan math/eigen warnings that make it difficult to figure out what needs to be fixed on my end (with `-I`).

It also makes the compilation experience a bit easier to digest. But it truly isn't needed otherwise.  

So out an abudence of caution, I have disabled it on every platform except the one I develop on :smile:

**Comment by mattfidler** [comment]
Thanks for the suggestion @bastistician, integrated it as suggested.

**Pull request merged**
