### PR TITLE
Add RcppParallel linker flags for StanHeaders 2.26 Compatibility

### PR DESCRIPTION
**Pull request by andrjohns**
This PR updates your package to additionally link against `RcppParallel`, which will be needed for the next version of `StanHeaders`

### CODE REVIEW

**Comment by mattfidler** [comment]
Thanks

**Comment by bgoodri** [comment]
Same deal as with nlmixr2est.

**Comment by mattfidler** [comment]
Same as `rxode2parse`

**Comment by mattfidler** [comment]
@bgoodri @andrjohns 

Cran wanted cpp17 instead of cpp14.  With the flags you supplied and cpp17 I have the following issue:

Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_rxode2ll.html>.

Please correct before 2023-03-31 to safely retain your package on CRAN.

The CRAN Team

Does this need cpp14?

**Comment by mattfidler** [comment]
I can revert everything but I sm sure that doesn't help you.

**Comment by bgoodri** [comment]
Don't revert; we'll figure it out. Does nlmixr2 compile with the C++14 standard (but continuing to link to TBB)?

**Comment by andrjohns** [comment]
I believe you just need to replace `-DBOOST_NO_AUTO_PTR` with `-D_HAS_AUTO_PTR_ETC=0` in your Makevars files

**Comment by mattfidler** [comment]
Thanks @andrjohns 

I will try it out and resubmit to CRAN.

@bgoodri it linked without linking to the tbb threads library in the past, so I'm unsure.  I use the backward AD engine only if that helps answer your question.

I separated out the stan pieces from `nlmixr2est` proper because `armadillo` and `eigen` were having problems.  This should be fine.

**Comment by bgoodri** [comment]
With the current StanHeaders / rstan on CRAN, linking to TBB was somewhat optional and it would work either way if TBB was not utilized. With the next StanHeaders / rstan, linking to TBB is mandatory and there will be a linker error otherwise. So, the change to the linker flags is necessary for the next StanHeaders to have a smooth(er) path to CRAN.

The stuff about the C++ standard and `-D_HAS_AUTO_PTR_ETC=0` is separate from TBB considerations and is mostly due to CRAN wanting everyone to use the C++17 standard for the next R release.

**Pull request merged**
